name: Build and release

on:
  push:
    tag: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Yolo Build
      run: cargo build --verbose --release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/site-gen"
        body: "Automated Yolo release -- use at your own risk"
